route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'test@gmail.com'
        auth_password: "mdpp"
        from: 'test@gmail.com'
        to: 'test2@gmail.com'